version: '2'
services:
  mysql:
    image: droptoken-mysql
    tmpfs:
      - /var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=appuser
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=appuser
      - MYSQL_DATABASE=droptoken
    ports:
      - "3306:3306"